# NumPy Basics

NumPy is the fundamental package for numerical computing in Python. It provides:
- **ndarray**: a fast, memory-efficient multidimensional array
- Vectorized operations (no explicit loops needed)
- Linear algebra, random number generation, Fourier transforms, etc.

In [1]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.6


## 1. Creating Arrays

In [2]:
# From a Python list
a = np.array([1, 2, 3, 4, 5])
print("1D array:", a)

# 2D array
b = np.array([[1, 2], [3, 4], [5, 6]])
print("2D array:\n", b)

# Built-in constructors
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Identity:\n", np.eye(3))
print("Range:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))
print("Random:", np.random.rand(3))

1D array: [1 2 3 4 5]
2D array:
 [[1 2]
 [3 4]
 [5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random: [0.35503426 0.96075189 0.40987789]


## 2. Array Attributes

In [3]:
arr = np.random.randn(3, 4)
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Total elements:", arr.size)
print("Data type:", arr.dtype)
print("Item size (bytes):", arr.itemsize)

Array:
 [[-1.31527815 -0.14171069  0.65917335  0.13988927]
 [ 0.9628     -1.59573412  1.04637308 -1.58137948]
 [ 1.58982145 -0.07450052 -0.23082701  1.78702134]]
Shape: (3, 4)
Number of dimensions: 2
Total elements: 12
Data type: float64
Item size (bytes): 8


## 3. Indexing and Slicing

In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Array:\n", arr)
print("\nFirst row:", arr[0])
print("Element at [1, 2]:", arr[1, 2])
print("First column:", arr[:, 0])
print("Last row:", arr[-1])
print("Submatrix (first 2 rows, last 2 cols):\n", arr[:2, 1:])
print("Step slicing:", np.arange(10)[::2])

Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

First row: [10 20 30]
Element at [1, 2]: 60
First column: [10 40 70]
Last row: [70 80 90]
Submatrix (first 2 rows, last 2 cols):
 [[20 30]
 [50 60]]
Step slicing: [0 2 4 6 8]


## 4. Boolean Indexing & Fancy Indexing

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean mask
mask = arr > 3
print("Mask:", mask)
print("Values > 3:", arr[mask])

# Fancy indexing with integer arrays
indices = [0, 2, 4]
print("Selected positions:", arr[indices])

Mask: [False False False  True  True  True]
Values > 3: [4 5 6]
Selected positions: [1 3 5]


## 5. Vectorized Operations

In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a + b =", a + b)
print("a * b =", a * b)
print("a ** 2 =", a ** 2)
print("np.sqrt(a) =", np.sqrt(a))
print("np.exp(a) =", np.exp(a))
print("np.sin(a) =", np.sin(a))

a + b = [11 22 33]
a * b = [10 40 90]
a ** 2 = [1 4 9]
np.sqrt(a) = [1.         1.41421356 1.73205081]
np.exp(a) = [ 2.71828183  7.3890561  20.08553692]
np.sin(a) = [0.84147098 0.90929743 0.14112001]


## 6. Broadcasting

NumPy automatically expands dimensions so arrays of different shapes can be used together.

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row = np.array([10, 20, 30])

print("Array:\n", arr)
print("Row:", row)
print("Array + row (broadcast):\n", arr + row)
print("\nMultiply by scalar:", arr * 2)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row: [10 20 30]
Array + row (broadcast):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Multiply by scalar: [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## 7. Aggregations

In [8]:
arr = np.random.randn(3, 4)
print("Array:\n", arr)
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Std:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("\nColumn means (axis=0):", np.mean(arr, axis=0))
print("Row sums (axis=1):", np.sum(arr, axis=1))

Array:
 [[ 0.68440607 -0.04691591  0.54338782  0.43161668]
 [ 1.24488457 -0.76939317 -0.08705165  0.96625309]
 [ 2.16494753 -0.76806535 -0.4758254   0.44871576]]

Sum: 4.336960035769483
Mean: 0.3614133363141236
Std: 0.8252446692436175
Min: -0.7693931701817452
Max: 2.1649475292866365

Column means (axis=0): [ 1.36474606 -0.52812481 -0.00649641  0.61552851]
Row sums (axis=1): [1.61249465 1.35469284 1.36977254]


## 8. Reshaping & Transposing

In [9]:
arr = np.arange(12)
print("Original:", arr)
print("Reshaped (3, 4):\n", arr.reshape(3, 4))
print("Flattened back:", arr.reshape(3, 4).ravel())
print("Transpose:\n", arr.reshape(3, 4).T)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened back: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 9. Linear Algebra Basics

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A @ B (matrix product):\n", A @ B)
print("\nnp.dot(A, B):\n", np.dot(A, B))
print("\nDeterminant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))
print("Eigenvalues:", np.linalg.eigvals(A))

A @ B (matrix product):
 [[19 22]
 [43 50]]

np.dot(A, B):
 [[19 22]
 [43 50]]

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]


## 10. Copies vs Views

Slicing returns a **view** (no copy). Fancy/boolean indexing returns a **copy**.

In [11]:
arr = np.array([1, 2, 3, 4])

# Slice → view (modifying view affects original)
view = arr[:2]
view[0] = 99
print("After view modification, original:", arr)

# Copy explicitly
arr2 = np.array([1, 2, 3, 4])
copy = arr2[:2].copy()
copy[0] = 99
print("After copy modification, original:", arr2)

After view modification, original: [99  2  3  4]
After copy modification, original: [1 2 3 4]
